openapi: 3.0.4
info:
  title: Bonafide Scoring & Graph API
  version: 1.0.0
  description: API for calculating user scores and generating graphs based on OJS actor data.

servers:
  - url: /bonafide
    description: Base path for all endpoints

paths:
  /login:
    post:
      summary: Exchange credentials for JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  format: password
                  example: secret
              required:
                - username
                - password
      responses:
        '200':
          description: JWT token response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: JWT access token

  /scores/calculate:
    post:
      summary: Calculate scores for one or more users
      description: Used for both bulk score calculation and single-user recalculation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/User"
      responses:
        '200':
          description: List of users with calculated scores
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserWithScores"

  /graphs/generate:
    post:
      summary: Generate a graph for a specific user
      description: This endpoint is under development. Request/response format is subject to change.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Placeholder schema for graph generation input
              properties:
                user:
                  $ref: "#/components/schemas/UserWithScores"
                options:
                  type: object
                  description: Additional graph options (TBD)
      responses:
        '200':
          description: Placeholder graph data response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GraphData"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: Internal OJS ID
          example: "u123"
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john@example.com"
        affiliation:
          type: array
          description: List of user affiliations (institutions, organizations, etc.)
          items:
            type: string
          example:
            - "University of Example"
            - "Research Institute XYZ"
        orcid:
          type: string
          description: ORCID identifier for the user
          pattern: "^\\d{4}-\\d{4}-\\d{4}-\\d{3}[\\dX]$"
          example: "0000-0002-1825-0097"
      required:
        - id
        - name
        - email

    UserWithScores:
      allOf:
        - $ref: "#/components/schemas/User"
        - type: object
          properties:
            subscores:
              type: array
              items:
                $ref: "#/components/schemas/SubscoreCategory"
          required:
            - subscores

    SubscoreCategory:
      type: object
      properties:
        attributeKey:
          type: string
          description: Category name (e.g., Reputation, Activity, Verification)
          example: Reputation
        total:
          type: number
          description: Total score for the category
          example: 200
        details:
          type: object
          description: Mapping of sub-metrics to scores
          additionalProperties:
            type: number
          example:
            Academic Presence: 120
            Educator Career: 80
      required:
        - attributeKey
        - total
        - details

    GraphData:
      type: object
      description: Placeholder schema for generated graph output (TBD)